FROM elan-base:latest

RUN apt-get update && apt-get install -y \
    systemd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-webui.txt /requirements-webui.txt
RUN pip install --no-cache-dir -r /requirements-webui.txt

EXPOSE 80
