FROM elan-base:latest

RUN apt-get update && apt-get install -y \
    cifs-utils \
    smbclient \
    samba \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-base.txt /requirements-base.txt
RUN pip install --no-cache-dir -r /requirements-base.txt
