FROM python:3.12-slim

# Dépendances système de base
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Dépendances Python communes
COPY requirements-base.txt /requirements-base.txt
RUN pip install --no-cache-dir -r /requirements-base.txt
