FROM elan-base-heavy:latest

RUN apt-get update && apt-get install -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-pdf.txt /requirements-pdf.txt
RUN pip install --no-cache-dir -r /requirements-pdf.txt
