FROM elan-base-heavy:latest

RUN apt-get update && apt-get install -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /app

# Dépendances Python communes
COPY requirements-watchdog.txt /requirements-watchdog.txt
RUN pip install --no-cache-dir -r /requirements-watchdog.txt
